# Generated by Django 3.0.8 on 2020-07-07 17:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='creationdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 7, 17, 5, 39, 720602, tzinfo=utc)),
        ),
    ]
