# Generated by Django 3.0.8 on 2020-07-07 17:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200707_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='creationdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 7, 17, 6, 8, 370029, tzinfo=utc)),
        ),
    ]
