# Generated by Django 3.0.7 on 2020-08-13 17:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20200808_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='creationdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 17, 2, 1, 550482, tzinfo=utc)),
        ),
    ]
