# Generated by Django 3.0.7 on 2020-07-26 18:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20200707_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='creationdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 26, 18, 12, 13, 8411, tzinfo=utc)),
        ),
    ]
