# Generated by Django 3.0.7 on 2020-07-26 20:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_auto_20200726_2014'),
        ('profiles', '0008_auto_20200726_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sharedfiles',
            field=models.ManyToManyField(related_name='sharedfiles', to='uploads.File'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='creationdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 26, 20, 14, 41, 170200, tzinfo=utc)),
        ),
    ]
