# Generated by Django 3.0.7 on 2020-07-26 20:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0005_auto_20200726_2026'),
        ('profiles', '0009_auto_20200726_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sharedfolders',
            field=models.ManyToManyField(related_name='sharedfolders', to='uploads.Folder'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='creationdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 26, 20, 26, 56, 450004, tzinfo=utc)),
        ),
    ]
