# Generated by Django 3.0.7 on 2020-08-08 19:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20200726_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='creationdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 8, 19, 56, 8, 426849, tzinfo=utc)),
        ),
    ]
