# Generated by Django 3.0.7 on 2020-08-13 17:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0006_auto_20200808_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='images',
            field=models.FileField(blank=True, upload_to='album'),
        ),
        migrations.AlterField(
            model_name='file',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 17, 2, 1, 564800, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 17, 2, 1, 564768, tzinfo=utc)),
        ),
    ]
